config/routes.rb
Rails.application.routes.draw do

  namespace :api do 
    resources :lista_de_filmes
  end

  resources :generos
  resources :filmes, only: [:new, :create, :destroy, :edit, :update]
  get  "/filmes/busca" => "filmes#busca", as: :busca_filme
  root "filmes#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord

    belongs_to :genero
    validates :preco, presence: true


end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/controllers/api/lista_de_filmes_controller.rb
class Api::ListaDeFilmesController < ApplicationController

    def index
        @lista_de_filmes = Filme.all
        render json: @lista_de_filmes, status: :ok
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController

    def index
       #@filmes = Filme.order( :nome ).limit 10
         @filmes = Filme.joins(:genero)
    end

    def new
        @filme = Filme.new 
        @segunda_lista = Filme.joins(:genero) 
        @generos = Genero.all
     end

     def busca
        @nome = params[:nome]
        @busca_filmes = Filme.where "nome like ?", "%#{@nome}%"
        @generos = Genero.all
     end

     def edit
        id = params[:id]
        @filme = Filme.find(id)
        @segunda_lista = Filme.joins(:genero)
        @generos = Genero.all
         render :new
     end

     def update
         id = params[:id]
         @filme = Filme.find(id)
         valores = params.require(:filme).permit :nome, :descricao, :preco, :genero_id
         if @filme.update valores
         flash[:notice] = "Atualizado com sucesso"
         redirect_to new_filme_url
         else
            @generos = Genero.all
            render :new
         end
     end

    def create
        valores = params.require(:filme).permit :nome, :descricao, :preco, :genero_id
        @filme = Filme.new valores
        @segunda_lista = Filme.joins(:genero)

       if @filme.save
        flash[:notice] = "Cadastrado com sucesso"
        redirect_to new_filme_url
       else
        @generos = Genero.all
        render :new 
        end
    end

    def destroy
       id = params[:id]
        Filme.destroy id
        redirect_to new_filme_url
    end

end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: [:show, :edit, :update, :destroy]

  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
  end

  # GET /generos/new
  def new
    @genero = Genero.new
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(genero_params)

    respond_to do |format|
      if @genero.save
        format.html { redirect_to @genero, notice: 'Genero was successfully created.' }
        format.json { render :show, status: :created, location: @genero }
      else
        format.html { render :new }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1
  # PATCH/PUT /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        format.html { redirect_to @genero, notice: 'Genero was successfully updated.' }
        format.json { render :show, status: :ok, location: @genero }
      else
        format.html { render :edit }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero.destroy
    respond_to do |format|
      format.html { redirect_to generos_url, notice: 'Genero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genero_params
      params.require(:genero).permit(:nome)
    end
end

app/helpers/api/lista_de_filmes_helper.rb
module Api::ListaDeFilmesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/filmes/_filme.html.erb
<tr>
    <td><%= filme.nome  %></td>
    <td><%= filme.descricao  %></td>
    <td><%= filme.preco  %></td>
    <td><%= filme.genero.nome  %></td>
</tr>

app/views/filmes/busca.html.erb
        <table class="table table-bordered" >
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                </tr>
            </thead>
            <tbody>
                <%= render @busca_filmes %>
            </tbody>
        </table>

app/views/filmes/index.html.erb
        <table class="table table-bordered" >
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Genero</th>
                </tr>
            </thead>
            <tbody>
                <%= render  @filmes %>
            </tbody>
        </table>

app/views/filmes/new.html.erb
<% @filme.errors.full_messages.each do |message| %>
<div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>
<%if flash[:notice] %>
<div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>



<%=  form_for @filme  do |f| %>
    <div class="form-group">
            <%= f.label :nome %>
            <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
            <%= f.label :descricao %>
            <%= f.text_area :descricao, class: "form-control" %>
    </div>    

    <div class="form-inline">
        <div class="form-group">    
            <%= f.label :preco %>
            <%= f.number_field :preco, :step => 0.01, :min => 0.01, class: "form-control" %>
        </div>

     <div class="form-group">    
            <%= f.label :genero %>
            <%= f.collection_select :genero_id, @generos, :id, :nome, {}, class: "form-control" %>
    </div>

            <div class="form-group">
             <%= f.label "Cadastros" %>
            <%= f.submit "Salvar Filme", class: "btn btn-primary" %>
            <%= link_to 'Novo Genero', new_genero_path, class: "btn btn-warning" %>
            </div>
    </div>
<% end %>
<br/>




<table class="table table-bordered" >
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% @segunda_lista.each do |filme| %>
                <tr>
                    <td><%= filme.nome  %></td>
                    <td><%= filme.descricao  %></td>
                    <td><%= filme.preco  %></td>
                    <td>
                        <%= button_to  "Remover", filme, 
                            method: :delete, class: "btn btn-danger", 
                                data: {confirm: "Tem certeza que deseja Remover #{filme.nome}?" }%>
                    </td>

                   

                    <td>
                        <%= link_to  "Alterar", edit_filme_path(filme), class: "btn btn-primary"%>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>

app/views/generos/_form.html.erb
<%= form_with(model: genero, local: true) do |form| %>
  <% if genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genero.errors.count, "error") %> prohibited this genero from being saved:</h2>

      <ul>
      <% genero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :genero_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/generos/edit.html.erb
<h1>Editing Genero</h1>

<%= render 'form', genero: @genero %>

<%= link_to 'Show', @genero %> |
<%= link_to 'Back', generos_path %>

app/views/generos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generos.each do |genero| %>
      <tr>
        <td><%= genero.nome %></td>
        <td><%= link_to 'Show', genero %></td>
        <td><%= link_to 'Edit', edit_genero_path(genero) %></td>
        <td><%= link_to 'Destroy', genero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genero', new_genero_path %>

app/views/generos/new.html.erb
<h1>New Genero</h1>

<%= render 'form', genero: @genero %>

<%= link_to 'Back', generos_path %>

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @genero.nome %>
</p>

<%= link_to 'Edit', edit_genero_path(@genero) %> |
<%= link_to 'Back', generos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locadora Ruby Filmes </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= nav_bar brand: "Locadora Ruby Filmes", brand_link: root_url do %>
        <%= form_tag busca_filme_path, method: :get,  class: "navbar-form navbar-right" do %>
              <%= link_to  "Filmes", root_url, class: "navbar-form" %>
               <%= link_to  "Adminstrador", new_filme_path, class: "navbar-form" %>
            <div class="form-group">
              <%= text_field_tag :nome, @nome,  class: "form-control" %>
              <%= button_to  "Buscar", nil, class: "btn btn-default" %>
            </div>
        <% end %>
      <% end %>
        <div class="container">
    <%= yield %>
        </div>
  </body>
</html>